### ISSUE TITLE
Штамп основной надписи

### ISSUE THREAD

**Issue by lepota** [sergey-s-betke/eskdx#5]
Графы 27, 28, 29, 30 основной надписи в ГОСТе обозначены штриховой линией. Подскажите, где нужно исправить, чтоб эти графы вывелись штриховой линией?

**Comment by qmor** [comment]
Насколько я представляю, по аналогии с графами 24,25 - штриховая линия в ГОСТ при описании основной надписи означает опциональность этих граф, а не отрисовку пунктиром.

**Comment by lepota** [comment]
Извините, ГОСТ невнимательно прочел:

> 5.2 Основная надпись, дополнительные графы к ней и рамки выполняют сплошными основными и сплошными тонкими линиями по ГОСТ 2.303.
